models/search.py
from collections import defaultdict

from elasticsearch_dsl import (Document, Integer, Text, Boolean, Q, Keyword,
                               SF, Date, __version__)
from elasticsearch_dsl.connections import connections
from elasticsearch.helpers import parallel_bulk
from elasticsearch.exceptions import ConflictError
from flask_sqlalchemy import Pagination

from corelib.mc import cache
from corelib.db import rdb

from config import ES_HOSTS, PER_PAGE
from corelib.consts import K_POST, ONE_HOUR
from models.core import Post

connections.create_connection(hosts=ES_HOSTS)

# item.id, item.kind 获取对象并缓存
ITEM_MC_KEY = 'search:get({},{})'

# tag, page, order, per_page 只搜索热点post，缓存期为一个小时
POST_IDS_BY_TAG_MC_KEY = 'search:get_post_ids_by_tag(%s,%s,%s,%s)'

SEARCH_FIELDS = ['title^10', 'tags^5', 'content^2']
TARGET_MAPPER = {K_POST: Post}

gauss_sf = SF('gauss',
              created_at={
                  'origin': 'now',
                  'offset': '7d',
                  'scale': '10d'
              })

score_sf = SF('script_score',
              script={
                  'lang': 'painless',
                  'inline':
                  ("doc['n_likes'].value * 2 + doc['n_collects'].value")
              })


def get_item_data(item):
    """
    返回格式化的数据字典

    `item`: Post instance
    """
    try:
        content = item.content
    except AttributeError:
        content = ''

    try:
        tags = [tag.name for tag in item.tags]
    except AttributeError:
        tags = []

    return {
        'id': item.id,
        'tags': tags,
        'content': content,
        'title': item.title,
        'kind': item.kind,
        'n_likes': item.n_likes,
        'n_comments': item.n_comments,
        'n_collects': item.n_collects,
    }


class Item(Document):
    id = Integer()
    title = Text()
    kind = Integer()
    content = Text()
    n_likes = Integer()
    n_collects = Integer()
    n_comments = Integer()
    can_show = Boolean()
    created_at = Date()
    tags = Text(fields={'raw': Keyword()})

    class Index:
        name = 'test'

    @classmethod
    def add(cls, item):
        obj = cls(**get_item_data(item))
        obj.save()
        obj.clear_mc(item.id, item.kind)
        return obj

    @classmethod
    @cache(ITEM_MC_KEY.format('{id}', '{kind}'))
    def get(cls, id, kind):
        """ 获取对象并缓存 """
        s = cls.search()
        s.query = Q('bool', must=[Q('term', id=id), Q('term', kind=kind)])
        rs = s.execute()
        if rs:
            return rs.hits[0]

    @classmethod
    def clear_mc(cls, id, kind):
        rdb.delete(ITEM_MC_KEY.format(id, kind))

    @classmethod
    def delete(cls, item):
        rs = cls.get(item.id, item.kind)
        if rs:
            super(cls, rs).delete()
            cls.clear_mc(item.id, item.kind)
            return True
        return False

    @classmethod
    def update_item(cls, item):
        obj = cls.get(item.id, item.kind)
        if obj is None:
            return cls.add(item)

        kw = get_item_data(item)

        try:
            obj.update(**kw)
        except ConflictError:
            obj.clear_mc(item.id, item.kind)
            obj = cls.get(item.id, item.kind)
            obj.update(**kw)
        obj.clear_mc(item.id, item.kind)
        return True

    @classmethod
    def get_es(cls):
        search = cls.search()
        return connections.get_connection(search._using)

    @classmethod
    def bulk_update(cls, items, chunk_size=5000, op_type='update', **kwargs):
        # TODO NOT USED
        index = cls._index._name
        type = cls._doc_type.name

        objects = ({
            '_op_type': op_type,
            '_id': f'{doc.id}_{doc.kind}',
            '_index': index,
            '_type': type,
            '_source': doc.to_dict()
        } for doc in items)
        client = cls.get_es()
        rs = list(
            parallel_bulk(client, objects, chunk_size=chunk_size, **kwargs))
        for item in items:
            cls.clear_mc(item.id, item.kind)
        return rs

    @classmethod
    def new_search(cls, query, page, order_by=None, per_page=PER_PAGE):
        """ 根据关键字搜索结果，title权重最大, tag次之, content最小 """
        s = cls.search()
        s = s.query('multi_match', query=query, fields=SEARCH_FIELDS)  # 多行匹配

        if page < 1:
            page = 1
        start = (page - 1) * PER_PAGE
        s = s.extra(**{'from': start, 'size': per_page})
        if order_by is not None:
            s = s.sort(order_by)
        rs = s.execute()
        dct = defaultdict(list)
        for i in rs:
            dct[i.kind].append(i.id)

        items = []

        for kind, ids in dct.items():
            target_cls = TARGET_MAPPER.get(kind)
            if target_cls:
                items_ = target_cls.get_multi(ids)
                items.extend(items_)
        # Fix elasticsearch-dsl for 7.x
        total = rs.hits.total.value if __version__[0] >= 7 else rs.hits.total
        return Pagination(query, page, per_page, total, items)

    @classmethod
    @cache(POST_IDS_BY_TAG_MC_KEY %
           ('{tag}', '{page}', '{order_by}', '{per_page}'), ONE_HOUR)
    def get_post_ids_by_tag(cls, tag, page, order_by=None, per_page=PER_PAGE):
        """ 只搜索热点post，缓存期为一个小时 """
        s = cls.search()
        s = s.query(Q('bool', must=Q('term', kind=K_POST)))
        if page < 1:
            page = 1
        start = (page - 1) * PER_PAGE
        s = s.extra(**{'from': start, 'size': per_page})
        if order_by is not None:
            if order_by == 'hot':
                s = s.query(Q('function_score',
                              functions=[gauss_sf, score_sf]))  # 使用高斯函数查找 noqa
            else:
                s = s.sort(order_by)
        rs = s.execute()
        ids = [obj.id for obj in rs]
        # Fix elasticsearch-dsl for 7.x
        total = rs.hits.total.value if __version__[0] >= 7 else rs.hits.total
        return Pagination(tag, page, per_page, total, ids)

models/user.py
import os
from flask_security import UserMixin, RoleMixin

import requests

from corelib.db import db
from config import UPLOAD_FOLDER
from corelib.utils import generate_id
from models.contact import Contact, userFollowStats

roles_users = db.Table(
    'roles_users',  # noqa
    db.Column('user_id', db.Integer(), db.ForeignKey('users.id')),
    db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))


class Role(RoleMixin, db.Model):
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(191))


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    bio = db.Column(db.String(128), default='')
    name = db.Column(db.String(128), default='')
    nickname = db.Column(db.String(128), default='')
    email = db.Column(db.String(191), default='')
    password = db.Column(db.String(191))
    website = db.Column(db.String(191), default='')
    github_url = db.Column(db.String(191), default='')
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String(100))
    current_login_ip = db.Column(db.String(100))
    login_count = db.Column(db.Integer)
    active = db.Column(db.Boolean())
    icon_color = db.Column(db.String(7))
    confirmed_at = db.Column(db.DateTime())
    company = db.Column(db.String(191), default='')
    avatar_id = db.Column(db.String(20), default='')
    roles = db.relationship('Role',
                            secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

    __table_args__ = (
        db.Index('idx_name', name),
        db.Index('idx_email', email),
    )

    def url(self):
        return '/user/{}'.format(self.id)

    @property
    def github_id(self):
        return self.github_url.split('/')[-1]

    @property
    def avatar_path(self):
        avatar_id = self.avatar_id
        return '' if not avatar_id else '/static/avatars/{}.png'.format(
            avatar_id)

    def update_avatar(self, avatar_id):
        self.avatar_id = avatar_id
        self.save()

    def upload_avatar(self, img):
        avatar_id = generate_id()
        filename = os.path.join(UPLOAD_FOLDER, 'avatars',
                                '{}.png'.format(avatar_id))

        if isinstance(img, str) and img.startswith('http'):
            r = requests.get(img, stream=True)
            if r.status_code == 200:
                with open(filename, 'wb') as f:
                    for chunk in r.iter_content(1024):
                        f.write(chunk)
        else:
            img.save(filename)
        self.update_avatar(avatar_id)

    def follow(self, from_id):
        ok, _ = Contact.create(to_id=self.id, from_id=from_id)
        return ok

    def unfollow(self, from_id):
        contact = Contact.get_follow_item(from_id, self.id)
        if contact:
            contact.delete()
        return True if contact else False

    def is_followed_by(self, user_id):
        contact = Contact.get_follow_item(user_id, self.id)
        return bool(contact)

    @property
    def n_following(self):
        return self._follow_stats[1]

    @property
    def n_followers(self):
        return self._follow_stats[0]

    @property
    def _follow_stats(self):
        stats = userFollowStats.get(self.id)
        return (stats.follower_count, stats.following_count) if stats else (0, 0)  # noqa

    def delete(self):
        from models.like import LikeItem
        from models.collect import CollectItem
        from models.comment import CommentItem

        super().delete()
        for cond in (Contact.from_id, Contact.to_id):
            for contact in Contact.query.filter(cond == self.id):
                contact.delete()  # 注意，如果放在sqlalchemy的清理钩子里，会报错

        for cls_type in (LikeItem, CollectItem, CommentItem):
            for like in cls_type.query.filter_by(user_id=self.id):
                like.delete()

views/account.py
from flask import request, abort, render_template
from flask.blueprints import Blueprint
from flask_security import login_required

from models.user import User
from models.core import Post
from models.like import LikeItem
from models.collect import CollectItem
from models.contact import Contact
from corelib.utils import AttrDict

bp = Blueprint('account', __name__)


@bp.route('/landing')
def landing():
    type = request.args.get('type')
    type_map = {
        'reset': '重置',
        'confirm': '确认',
        'register': '激活',
        'confirmed': '已确认'
    }
    email = request.args.get('email')
    if not email:
        abort(404)
    if type not in type_map:
        type = 'register'
    action = type_map.get(type)
    return render_template('security/landing.html', **locals())


@bp.route('/settings/', methods=['GET', 'POST'])
@login_required
def settings():
    notice = False
    if request.method == 'POST':
        # 没有验证字段，存在漏洞 :<
        user = request.user
        image = request.files.get('user_image')
        d = request.form.to_dict()
        d.pop('submit', None)
        form = AttrDict(d)
        github_id = form.github_id
        if github_id:
            form.github_url = f'https://github.com/{github_id}'
        del form.github_id
        user.update(**form)
        if image:
            user.upload_avatar(image)
        notice = True
    return render_template('settings.html', notice=notice)


# yapf: disable
@bp.route('/user/<identifier>/likes/')
def user_likes(identifier):
    return render_user_page(identifier, 'card.html', Post, 'like',
                            endpoint='account.user_likes')  # Fix pagination


@bp.route('/user/<identifier>/favorites/')
def user_favorites(identifier):
    return render_user_page(identifier, 'card.html', Post, 'collect',
                            endpoint='account.user_favorites')


@bp.route('/user/<identifier>/following/')
def user_following(identifier):
    return render_user_page(identifier, 'user.html', User, 'following',
                            endpoint='account.user_following')


@bp.route('/user/<identifier>/followers/')
def user_followers(identifier):
    return render_user_page(identifier, 'user.html', User, 'followers',
                            endpoint='account.user_followers')


@bp.route('/user/<identifier>/')
def user(identifier):
    return render_user_page(identifier, 'user.html', User,
                            endpoint='account.user')


def render_user_page(identifier, renderer, target_cls, type='following',
                     endpoint=None):
    user = User.get(identifier)
    if not user:
        abort(404)
    page = request.args.get('page', default=1, type=int)
    if type == 'collect':
        p = CollectItem.get_paginate_by_user(user.id, page=page)
    elif type == 'like':
        p = LikeItem.get_paginate_by_user(user.id, page=page)
    elif type == 'following':
        p = Contact.get_following_paginate(user.id, page=page)
    elif type == 'followers':
        p = Contact.get_followers_paginate(user.id, page=page)
    p.items = target_cls.get_multi(p.items)
    return render_template(renderer, **locals())
# yapf: enable

templates/_macros.html
{% macro card(post, show_comment=True) %}
  {% set author = post.author %}
  {% set is_liked = post.is_liked_by(request.user_id) %}
  {% set is_collected = post.is_collected_by(request.user_id) %}
  {% set is_followed = author.is_followed_by(request.user_id) %}

  <div class="post detail">
    <div class="btn-group-vertical upvote">
      <a id="like-button-{{ post.id }}" class="btn btn-default btn-xs like-button {% if is_liked %}liked{% endif %}" rel="nofollow" data-url="post/{{ post.id }}/like" data-original-title="点赞">
        <i class="iconfont {% if is_liked %}toutiao-thumbsup{% else %}toutiao-thumbsoup{% endif %}"></i> <span>{{ post.n_likes }}</span>
      </a>

      <a id="favorite-button-{{ post.id }}" class="btn btn-default btn-xs collect-button {% if is_collected %}collected{% endif %}" rel="nofollow" data-method="post" data-url="post/{{ post.id }}/collect" data-original-title="收藏">
        <i class="iconfont {% if is_collected %}toutiao-bookmark{% else %}toutiao-bookmarko{% endif %}"></i>
      </a>
    </div>

    <div class="content">
      <h3 class="title">
        <a target="_blank" rel="external" title="{{ post.title }} - 开发者头条" href="{{ post.orig_url }}">
          {{ post.title }}
        </a>
      </h3>
      <p class="summary"><a href="{{ post.url() }}">{{ post.abstract_content }}</a></p>
      <div class="meta">
        {{ post.netloc }}
        {% if show_comment %}
        <span>
          <i class="iconfont {% if post.n_comments %}toutiao-comment{% else %}toutiao-commento{% endif %}"></i> {{ post.n_comments }}
        </span>
        {% endif %}
      </div>
    </div>

<div class="user-info">
  <div class="user-avatar">
    <a title="{{ author.name }} - 开发者头条" href="{{ author.url() }}">
      <img width="32" alt="{{ author.name }} - 独家号" src="{{ author.avatar_path }}">
    </a>
  </div>

  <div class="info">
    <h5>作者</h5>

    <a href="{{ author.url() }}"><img width="48" alt="{{ author.name }} - 开发者头条" src="{{ author.avatar_path }}"></a>

    <h4 class="m-b-xs">{{ author.name }}</h4>

    <p class="bio">{{ author.bio }}</p>
    <a class="btn btn-info btn-xs follow-button {% if is_followed %}followed{% endif %}" data-disable-with="请稍候..." rel="nofollow" data-url="{{ author.url() }}/follow">
      <i class="iconfont toutiao-eye"></i>{% if is_followed %}已{% endif %}关注TA
    </a>
  </div>
</div>

<div class="subject-name">
  <a href="{{ author.url() }}">{{ author.name }}</a></div>

  </div>
{% endmacro %}

{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="...">
  <ul class="pagination">
    {% if pagination.has_prev %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}">Prev &laquo;</a>
    </li>
    {% endif %}

    {% if pagination %}
      {%- for page in pagination.iter_pages() %}
      {% if page %}
        {% if pagination.has_next %}
        <li class="page-item {% if page == pagination.page %}active{% endif %}">
          <a class="page-link" href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a>
        </li>
        {% endif %}
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">...</a>
        </li>
      {% endif %}
      {%- endfor %}
    {% endif %}

    {% if pagination.has_next %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}">Next &raquo;</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endmacro %}

{% macro render_comment(comment) %}
{% set user = comment.user %}
<div class="comment media">
  <a class="media-left" href="{{ user.url() }}"><img src="{{ user.avatar_path }}" alt="Thumb"></a>
  <div class="media-body">
    <h4 class="media-heading">{{ user.name }}<small class="date">{{ comment.created_at }}</small></h4>
    <div>{{ comment.content }}</div>
  </div>
</div>
{% endmacro %}

{% macro render_user(user) %}
<div class="media" id="follows-{{ user.id }}">
  <div class="media-left">
    <a href="{{ user.url() }}"><img width="48" height=48 class="media-object img-circle" alt="{{ user.name }} - 开发者头条" src="{{ user.avatar_path }}"></a>
  </div>

  <div class="media-body">
    <h4 class="media-heading m-b-xs">
      <a title="{{ user.name }} - 开发者头条" href="{{ user.url() }}">{{ user.name }}</a>

      <small class="pull-right" id="followers-{{ user.id }}-count">
        <span>{{ user.n_followers }}</span><span>关注者</span>
      </small>
    </h4>

    <div class="bio">{{ user.bio }}</div>
  </div>
</div>
{% endmacro %}

templates/base.html
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
      <title>{% block title %}开发者头条{% endblock %}</title>
      <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
      <script src="{{url_for('static', filename='js/jquery-3.3.1.min.js')}}"></script>
      <script src="{{url_for('static', filename='js/popper.min.js')}}"></script>
      <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
      <script src="{{url_for('static', filename='dist/base.js')}}"></script>
    {% endblock %}
    </head>
    <body>
      <header class="navbar">
        <div class="container">
          <ul class="nav {% if request.user %}navbar-right{% endif %}">
            <li class="nav-item">
              <a class="nav-link" href="/">首页</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/tag/python/">Python</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/search">搜索</a>
            </li>
            {% if request.user %}
            <li class="dropdown profile">
              <a href="" class="dropdown-toggle clear navbar-profile" data-toggle="dropdown" aria-expanded="true">
                <span><img width="25" height="25" src="{{ request.user.avatar_path }}"></span> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li class="dropdown-item"><a href="{{ url_for('account.user_likes', identifier=request.user.id) }}">我的点赞</a></li>
                <li class="dropdown-item"><a href="{{ url_for('account.user_favorites', identifier=request.user.id) }}">我的收藏</a></li>
                <li class="dropdown-item"><a href="{{ url_for('account.user_following', identifier=request.user.id) }}">我的关注</a></li>
                <li class="dropdown-item"><a href="{{ url_for('account.settings') }}">个人设置</a></li>
                <li class="dropdown-item"><a href="/logout">退出</a></li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="/login">登录</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/register">注册</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </header>
      <div id="main">
        <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </div>
      <footer>
        {% block footer %}
          <p class="text-center">
            <a href="/about">关于我们</a>
            <a href="/tags">标签</a>
          </p>
          <p class="text-center">© 2018-2019</p>
        {% endblock %}
      </footer>
    </body>
    {% block bottomscript %}
    {% endblock %}
</html>

templates/card.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}搜索 - 头条{% endblock %}

{% block bottomscript %}
{{ super() }}
  <script src="{{url_for('static', filename='dist/card.js')}}"></script>
{% endblock %}

{% block content %}
  {% for post in p.items %}
    {{ macros.card(post) }}
  {% endfor %}
  {{ macros.render_pagination(p, endpoint, identifier=identifier) }}  <!-- Fix pagination -->
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block bottomscript %}
  {{ super() }}
  <script src="{{url_for('static', filename='dist/index.js')}}"></script>
{% endblock %}

{% block content %}
  {% for post in posts.items %}
  {{ macros.card(post) }}
  {% endfor %}
  {{ macros.render_pagination(posts, 'index.index') }}
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block head %}
  {{ super() }}
  <meta name="url" content="{{ request.url }}">
  <meta name="title" content="{{ post.title }}">
  <meta name="description" content="{{ post.abstract_content }}">
  <script src="{{url_for('static', filename='js/qrcode.min.js')}}"></script>
{% endblock %}

{% block bottomscript %}
  {{ super() }}
  <script src="{{url_for('static', filename='dist/post.js')}}"></script>
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  {% set url = post.url() %}
  {{ macros.card(post, False) }}
  <div class="post-tags">
    {% for tag in post.tags %}
      <a class="btn btn-default btn-rounded btn-xs" href="{{ tag.url() }}">{{ tag.name }}</a>
    {% endfor %}
  </div>
  <div class="social-share-button text-center" data-title="{{ post.title }} {{ url }} 分享自 @{{ post.author.name }}" data-type="text" data-url={{ url }}>
    <h5>分享到</h5>
    <a class="btn btn-danger share-weibo" rel="external nofollow" data-site="weibo" href="javascript;;"><i class="iconfont toutiao-weibo"></i> 微博</a>
    <span class="dropdown weixin-qrcode-dropdown">
      <button class="btn btn-success" type="button" data-toggle="dropdown"><i class="iconfont toutiao-weixin"></i> 微信</button>
      <span class="dropdown-menu weixin-qrcode-dropdown-menu" data-url="{{ url }}">
        <span id="weixin-qrcode" data-url="{{ url }}"></span>
      </span>
    </span>
  </div>

  <div class="post-comment-form">
    <span>评论 ({{ post.n_comments }})</span>

    {% if not request.user %}
    <div class="login-actions">
      <a class="btn btn-success" href="/signin">登录后评论</a>
    </div>
    {% else %}
    <form id="comment-form" novalidate="novalidate" class="new_comment" data-url="post/{{ post.id }}/comment" accept-charset="UTF-8" method="post">
      <div class="form-group text required comment_content">
        <textarea rows="5" class="text required comment-content form-control" id="comment-content"></textarea>
      </div>
      <div class="text-right">
        <input type="submit" id="comment-submit" name="commit" value="提 交" class="btn btn-default btn-info">
      </div>
    </form>
    {% endif %}
  </div>

  <div id="comments" class="comments">
    {% for comment in post.get_comments(None) %}
    {{ macros.render_comment(comment) }}
    {% endfor %}
  </div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}搜索 - 头条{% endblock %}

{% block head %}
{{ super() }}
  <script src="{{url_for('static', filename='dist/search.js')}}"></script>
{% endblock %}

{% block bottomscript %}
{{ super() }}
  <script src="{{url_for('static', filename='dist/card.js')}}"></script>
{% endblock %}

{% block content %}
  <form action="/search" accept-charset="UTF-8" method="get" _lpchecked="1">
    <div class="input-group">
      <input type="text" name="q" id="q" value="{{query}}" class="form-control" placeholder="搜索 Python">
      <span class="input-group-btn">
        <button type="submit" class="btn btn-default search">
          <i class="iconfont toutiao-search"></i>
        </button>
      </span>
    </div>
  </form>

  {% for post in posts.items %}
    {{ macros.card(post) }}
  {% endfor %}
  {{ macros.render_pagination(posts, 'index.search', q=query) }}
{% endblock %}

templates/settings.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}个人设置{% endblock %}

{% block head %}
{{ super() }}
  <script src="{{url_for('static', filename='dist/settings.js')}}"></script>
{% endblock %}

{% block content %}
{% set user = request.user  %}
{% if notice %}
  <div id="notice-wrapper" class="container"><div id="notice" class="alert alert-info">保存成功!</div></div>
{% endif %}
<h3 class="text-center">个人设置</h3>
<br>
<form class="form-horizontal" data-toggle="validator" novalidate="novalidate" enctype="multipart/form-data" action="/settings/" accept-charset="UTF-8" method="post">

<div class="form-group">
  <label class="string optional col-sm-2 control-label" for="user_avatar">头像:</label>
  <div class="col-sm-10">
    <img class="user-avatar" src="{{ user.avatar_path }}">
    <input class="avatar-field" type="file" name="user_image" id="user_image">
  </div>
</div>

<div class="form-group string optional user_uname">
  <label class="string optional col-sm-2 control-label" for="nickname">昵称:</label>
  <div class="col-sm-10">
    <input class="string optional form-control" type="text" value="{{ user.nickname }}" name="nickname" id="username">
  </div>
</div>

<div class="form-group">
  <label class="string optional col-sm-2 control-label" for="github_id">GitHub用户名:</label>
  <div class="col-sm-10">
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">https://github.com/</span>
      <input class="form-control" placeholder="username" type="text" value="{{ user.github_id }}" name="github_id" id="user_github">
    </div>
  </div>
</div>

<div class="form-group url optional user_blog">
  <label class="url optional col-sm-2 control-label" for="website">个⼈主⻚:</label>
  <div class="col-sm-10">
    <input value="{{ user.website }}" class="string url optional form-control" placeholder="http://" type="url" name="website" id="user_blog">
  </div>
</div>

<div class="form-group string optional user_bio">
  <label class="string optional col-sm-2 control-label" for="intro">一句话介绍:</label>
  <div class="col-sm-10">
    <input class="string optional form-control" placeholder="介绍下自己吧？" type="text" value="{{ user.bio or '' }}" name="bio" id="user_bio">
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <input type="submit" name="submit" value="保 存" class="btn btn-default">
  </div>
</div>

</form>
{% endblock %}